const UI_STATE = {
    isMouseHolded: false,
    startX: 0,
    startY: 0,
    dx: 0,
    dy: 0,
    AbsoulteDx: 0,
    AbsoulteDy: 0,
    isPlay: false,
    initMode: true,
    VIEWPORT_WIDTH: 800,
    VIEWPORT_HEIGHT: 600,
    CURSOR_COLOR: "#ffffff",
    CURSOR_WIDTH: 10,
    CURSOR_HEIGHT: 10,
    cursorX: 0,
    cursorY: 0,
    isRenderCursor: false,
}
export { UI_STATE };